blank_issues_enabled: false
contact_links:
  - name: ğŸ“„ é˜…è¯»æ–‡æ¡£
    url: https://www.kancloud.cn/ken678/yzncms
    about: å»ºè®®ä½ åœ¨åˆ›å»º Issue ä¹‹å‰ï¼Œä»”ç»†æŸ¥é˜… YznCMS å¼€å‘æ–‡æ¡£ï¼Œä»¥ä¾¿å¯¹å…¶æœ‰æ›´æ·±å…¥çš„äº†è§£ï¼Œå’Œæ›´å¥½åœ°åˆ†æé—®é¢˜ã€‚